import Vue from 'vue'
import { Tab, Tabs, Checkbox, Dialog, ActionSheet, Button, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, Grid, SwipeItem, GridItem, Icon, Rate } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(ActionSheet)
Vue.use(Rate)
Vue.use(Icon)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(Grid)
Vue.use(SwipeItem)
Vue.use(GridItem)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
